# Generated by Django 4.0.6 on 2023-08-23 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='spectator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spectatorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='showtime',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.film'),
        ),
        migrations.AddField(
            model_name='showtime',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.screenhall'),
        ),
        migrations.AlterUniqueTogether(
            name='film',
            unique_together={('title', 'director')},
        ),
    ]
