# Generated by Django 4.0.6 on 2022-08-07 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_film_screencinema_alter_spectator_wallet_showtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtime',
            name='price_currency',
        ),
        migrations.AlterField(
            model_name='showtime',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ticket price'),
        ),
        migrations.AlterField(
            model_name='spectator',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Your account balance'),
        ),
    ]
