# Generated by Django 4.0.6 on 2023-08-25 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpectatorProfile',
        ),
    ]
