# Generated by Django 4.0.6 on 2022-08-27 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_showtime_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screencinema',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Name screen'),
        ),
        migrations.AlterField(
            model_name='spectator',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='showtime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='cinema.showtime', verbose_name='Showtime'),
        ),
    ]
