# Generated by Django 4.0.6 on 2022-09-19 08:13

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_alter_screencinema_name_alter_spectator_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 8, 12, 26, 438223, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='showtime',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
