# Generated by Django 4.0.6 on 2023-08-04 08:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_alter_showtime_options_remove_showtime_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='to_rental',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='attendance',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.film'),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ticket price'),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.screencinema'),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
