# Generated by Django 4.0.6 on 2023-08-25 08:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_admin', '0002_alter_cinemauser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpectatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='account')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'spectator profile',
                'verbose_name_plural': 'spectator profiles',
                'db_table': 'spectator_profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
