# Generated by Django 4.0.6 on 2023-08-25 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_admin', '0003_spectatorprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spectatorprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='spectatorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
