# Generated by Django 4.0.6 on 2023-08-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_admin', '0004_remove_spectatorprofile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemauser',
            name='role',
            field=models.CharField(choices=[('AD', 'Administrator'), ('SP', 'Spectator')], default='SP', max_length=2, verbose_name='cinema system role'),
        ),
    ]
